// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OfficeAdministrationTool.Entity
{
    public partial class User
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public DateTime DateCreated { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DateModified { get; set; }
        public string ResetToken { get; set; }
        public DateTime? ResetTokenExpirationTime { get; set; }
        public bool? IsActive { get; set; }
    }
}